/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


 /* Includes the header in the wrapper code */
 #include "glfs.h"
 

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1new(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  glfs_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (glfs_t *)glfs_new((char const *)arg1);
  *(glfs_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1set_1volfile(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)glfs_set_volfile(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1set_1volfile_1server(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jint jarg4) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (int)jarg4; 
  result = (int)glfs_set_volfile_server(arg1,(char const *)arg2,(char const *)arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1set_1logging(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (int)glfs_set_logging(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1init(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  result = (int)glfs_init(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fini(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  result = (int)glfs_fini(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1open(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  glfs_fd_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (glfs_fd_t *)glfs_open(arg1,(char const *)arg2,arg3);
  *(glfs_fd_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1creat(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  mode_t arg4 ;
  mode_t *argp4 ;
  glfs_fd_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  argp4 = *(mode_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null mode_t");
    return 0;
  }
  arg4 = *argp4; 
  result = (glfs_fd_t *)glfs_creat(arg1,(char const *)arg2,arg3,arg4);
  *(glfs_fd_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1close(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  result = (int)glfs_close(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1from_1glfd(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  glfs_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  result = (glfs_t *)glfs_from_glfd(arg1);
  *(glfs_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1set_1xlator_1option(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jstring jarg4) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  result = (int)glfs_set_xlator_option(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1read(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  int arg4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (int)jarg4; 
  result = glfs_read(arg1,arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  int arg4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (int)jarg4; 
  result = glfs_write(arg1,(void const *)arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1read_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4, jlong jarg5, jlong jarg6) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  int arg4 ;
  glfs_io_cbk arg5 = (glfs_io_cbk) 0 ;
  void *arg6 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(glfs_io_cbk *)&jarg5; 
  arg6 = *(void **)&jarg6; 
  result = (int)glfs_read_async(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1write_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4, jlong jarg5, jlong jarg6) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  int arg4 ;
  glfs_io_cbk arg5 = (glfs_io_cbk) 0 ;
  void *arg6 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(glfs_io_cbk *)&jarg5; 
  arg6 = *(void **)&jarg6; 
  result = (int)glfs_write_async(arg1,(void const *)arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1readv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct iovec *arg2 = (struct iovec *) 0 ;
  int arg3 ;
  int arg4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct iovec **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = glfs_readv(arg1,(struct iovec const *)arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1writev(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct iovec *arg2 = (struct iovec *) 0 ;
  int arg3 ;
  int arg4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct iovec **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = glfs_writev(arg1,(struct iovec const *)arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1readv_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jlong jarg5, jlong jarg6) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct iovec *arg2 = (struct iovec *) 0 ;
  int arg3 ;
  int arg4 ;
  glfs_io_cbk arg5 = (glfs_io_cbk) 0 ;
  void *arg6 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct iovec **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(glfs_io_cbk *)&jarg5; 
  arg6 = *(void **)&jarg6; 
  result = (int)glfs_readv_async(arg1,(struct iovec const *)arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1writev_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jlong jarg5, jlong jarg6) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct iovec *arg2 = (struct iovec *) 0 ;
  int arg3 ;
  int arg4 ;
  glfs_io_cbk arg5 = (glfs_io_cbk) 0 ;
  void *arg6 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct iovec **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(glfs_io_cbk *)&jarg5; 
  arg6 = *(void **)&jarg6; 
  result = (int)glfs_writev_async(arg1,(struct iovec const *)arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1pread(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jint jarg5) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  off_t arg4 ;
  int arg5 ;
  off_t *argp4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  argp4 = *(off_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (int)jarg5; 
  result = glfs_pread(arg1,arg2,arg3,arg4,arg5);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1pwrite(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jint jarg5) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  off_t arg4 ;
  int arg5 ;
  off_t *argp4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  argp4 = *(off_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (int)jarg5; 
  result = glfs_pwrite(arg1,(void const *)arg2,arg3,arg4,arg5);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1pread_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  off_t arg4 ;
  int arg5 ;
  glfs_io_cbk arg6 = (glfs_io_cbk) 0 ;
  void *arg7 = (void *) 0 ;
  off_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  argp4 = *(off_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (int)jarg5; 
  arg6 = *(glfs_io_cbk *)&jarg6; 
  arg7 = *(void **)&jarg7; 
  result = (int)glfs_pread_async(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1pwrite_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  off_t arg4 ;
  int arg5 ;
  glfs_io_cbk arg6 = (glfs_io_cbk) 0 ;
  void *arg7 = (void *) 0 ;
  off_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (int)jarg3; 
  argp4 = *(off_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (int)jarg5; 
  arg6 = *(glfs_io_cbk *)&jarg6; 
  arg7 = *(void **)&jarg7; 
  result = (int)glfs_pwrite_async(arg1,(void const *)arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1preadv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jint jarg5) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct iovec *arg2 = (struct iovec *) 0 ;
  int arg3 ;
  off_t arg4 ;
  int arg5 ;
  off_t *argp4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct iovec **)&jarg2; 
  arg3 = (int)jarg3; 
  argp4 = *(off_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (int)jarg5; 
  result = glfs_preadv(arg1,(struct iovec const *)arg2,arg3,arg4,arg5);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1pwritev(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jint jarg5) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct iovec *arg2 = (struct iovec *) 0 ;
  int arg3 ;
  off_t arg4 ;
  int arg5 ;
  off_t *argp4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct iovec **)&jarg2; 
  arg3 = (int)jarg3; 
  argp4 = *(off_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (int)jarg5; 
  result = glfs_pwritev(arg1,(struct iovec const *)arg2,arg3,arg4,arg5);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1preadv_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct iovec *arg2 = (struct iovec *) 0 ;
  int arg3 ;
  off_t arg4 ;
  int arg5 ;
  glfs_io_cbk arg6 = (glfs_io_cbk) 0 ;
  void *arg7 = (void *) 0 ;
  off_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct iovec **)&jarg2; 
  arg3 = (int)jarg3; 
  argp4 = *(off_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (int)jarg5; 
  arg6 = *(glfs_io_cbk *)&jarg6; 
  arg7 = *(void **)&jarg7; 
  result = (int)glfs_preadv_async(arg1,(struct iovec const *)arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1pwritev_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct iovec *arg2 = (struct iovec *) 0 ;
  int arg3 ;
  off_t arg4 ;
  int arg5 ;
  glfs_io_cbk arg6 = (glfs_io_cbk) 0 ;
  void *arg7 = (void *) 0 ;
  off_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct iovec **)&jarg2; 
  arg3 = (int)jarg3; 
  argp4 = *(off_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (int)jarg5; 
  arg6 = *(glfs_io_cbk *)&jarg6; 
  arg7 = *(void **)&jarg7; 
  result = (int)glfs_pwritev_async(arg1,(struct iovec const *)arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1lseek(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  off_t arg2 ;
  int arg3 ;
  off_t *argp2 ;
  off_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  argp2 = *(off_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (int)jarg3; 
  result = glfs_lseek(arg1,arg2,arg3);
  {
    off_t * resultptr = (off_t *) malloc(sizeof(off_t));
    memmove(resultptr, &result, sizeof(off_t));
    *(off_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1truncate(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  off_t arg3 ;
  off_t *argp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(off_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg3 = *argp3; 
  result = (int)glfs_truncate(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1ftruncate(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  off_t arg2 ;
  off_t *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  argp2 = *(off_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg2 = *argp2; 
  result = (int)glfs_ftruncate(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1ftruncate_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  off_t arg2 ;
  glfs_io_cbk arg3 = (glfs_io_cbk) 0 ;
  void *arg4 = (void *) 0 ;
  off_t *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  argp2 = *(off_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(glfs_io_cbk *)&jarg3; 
  arg4 = *(void **)&jarg4; 
  result = (int)glfs_ftruncate_async(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1lstat(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  struct stat *arg3 = (struct stat *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(struct stat **)&jarg3; 
  result = (int)glfs_lstat(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1stat(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  struct stat *arg3 = (struct stat *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(struct stat **)&jarg3; 
  result = (int)glfs_stat(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fstat(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct stat *arg2 = (struct stat *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct stat **)&jarg2; 
  result = (int)glfs_fstat(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fsync(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  result = (int)glfs_fsync(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fsync_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  glfs_io_cbk arg2 = (glfs_io_cbk) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(glfs_io_cbk *)&jarg2; 
  arg3 = *(void **)&jarg3; 
  result = (int)glfs_fsync_async(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fdatasync(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  result = (int)glfs_fdatasync(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fdatasync_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  glfs_io_cbk arg2 = (glfs_io_cbk) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(glfs_io_cbk *)&jarg2; 
  arg3 = *(void **)&jarg3; 
  result = (int)glfs_fdatasync_async(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1access(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (int)glfs_access(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1symlink(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)glfs_symlink(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1readlink(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  size_t arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (size_t)jarg4; 
  result = (int)glfs_readlink(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1mknod(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  mode_t arg3 ;
  dev_t arg4 ;
  mode_t *argp3 ;
  dev_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(mode_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null mode_t");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(dev_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null dev_t");
    return 0;
  }
  arg4 = *argp4; 
  result = (int)glfs_mknod(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1mkdir(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  mode_t arg3 ;
  mode_t *argp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(mode_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null mode_t");
    return 0;
  }
  arg3 = *argp3; 
  result = (int)glfs_mkdir(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1unlink(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)glfs_unlink(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1rmdir(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)glfs_rmdir(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1rename(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)glfs_rename(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1link(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)glfs_link(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1opendir(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  glfs_fd_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (glfs_fd_t *)glfs_opendir(arg1,(char const *)arg2);
  *(glfs_fd_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1readdir_1r(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct dirent *arg2 = (struct dirent *) 0 ;
  struct dirent **arg3 = (struct dirent **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct dirent **)&jarg2; 
  arg3 = *(struct dirent ***)&jarg3; 
  result = (int)glfs_readdir_r(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1readdirplus_1r(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct stat *arg2 = (struct stat *) 0 ;
  struct dirent *arg3 = (struct dirent *) 0 ;
  struct dirent **arg4 = (struct dirent **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct stat **)&jarg2; 
  arg3 = *(struct dirent **)&jarg3; 
  arg4 = *(struct dirent ***)&jarg4; 
  result = (int)glfs_readdirplus_r(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1telldir(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  result = (long)glfs_telldir(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1seekdir(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = (long)jarg2; 
  glfs_seekdir(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1closedir(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  result = (int)glfs_closedir(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1statvfs(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  struct statvfs *arg3 = (struct statvfs *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(struct statvfs **)&jarg3; 
  result = (int)glfs_statvfs(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1chmod(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  mode_t arg3 ;
  mode_t *argp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(mode_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null mode_t");
    return 0;
  }
  arg3 = *argp3; 
  result = (int)glfs_chmod(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fchmod(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  mode_t arg2 ;
  mode_t *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  argp2 = *(mode_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null mode_t");
    return 0;
  }
  arg2 = *argp2; 
  result = (int)glfs_fchmod(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1chown(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  uid_t arg3 ;
  gid_t arg4 ;
  uid_t *argp3 ;
  gid_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(uid_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uid_t");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(gid_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null gid_t");
    return 0;
  }
  arg4 = *argp4; 
  result = (int)glfs_chown(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1lchown(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  uid_t arg3 ;
  gid_t arg4 ;
  uid_t *argp3 ;
  gid_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(uid_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uid_t");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(gid_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null gid_t");
    return 0;
  }
  arg4 = *argp4; 
  result = (int)glfs_lchown(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fchown(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  uid_t arg2 ;
  gid_t arg3 ;
  uid_t *argp2 ;
  gid_t *argp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  argp2 = *(uid_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uid_t");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(gid_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null gid_t");
    return 0;
  }
  arg3 = *argp3; 
  result = (int)glfs_fchown(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1utimens(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  struct timespec *arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(struct timespec **)&jarg3; 
  result = (int)glfs_utimens(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1lutimens(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  struct timespec *arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(struct timespec **)&jarg3; 
  result = (int)glfs_lutimens(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1futimens(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  struct timespec *arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(struct timespec **)&jarg2; 
  result = (int)glfs_futimens(arg1,arg2);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1getxattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  void *arg4 = (void *) 0 ;
  size_t arg5 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(void **)&jarg4; 
  arg5 = (size_t)jarg5; 
  result = glfs_getxattr(arg1,(char const *)arg2,(char const *)arg3,arg4,arg5);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1lgetxattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  void *arg4 = (void *) 0 ;
  size_t arg5 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(void **)&jarg4; 
  arg5 = (size_t)jarg5; 
  result = glfs_lgetxattr(arg1,(char const *)arg2,(char const *)arg3,arg4,arg5);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fgetxattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  char *arg2 = (char *) 0 ;
  void *arg3 = (void *) 0 ;
  size_t arg4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(void **)&jarg3; 
  arg4 = (size_t)jarg4; 
  result = glfs_fgetxattr(arg1,(char const *)arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1listxattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  void *arg3 = (void *) 0 ;
  size_t arg4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(void **)&jarg3; 
  arg4 = (size_t)jarg4; 
  result = glfs_listxattr(arg1,(char const *)arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1llistxattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  void *arg3 = (void *) 0 ;
  size_t arg4 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(void **)&jarg3; 
  arg4 = (size_t)jarg4; 
  result = glfs_llistxattr(arg1,(char const *)arg2,arg3,arg4);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1flistxattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  result = glfs_flistxattr(arg1,arg2,arg3);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1setxattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4, jlong jarg5, jint jarg6) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  void *arg4 = (void *) 0 ;
  size_t arg5 ;
  int arg6 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(void **)&jarg4; 
  arg5 = (size_t)jarg5; 
  arg6 = (int)jarg6; 
  result = (int)glfs_setxattr(arg1,(char const *)arg2,(char const *)arg3,(void const *)arg4,arg5,arg6);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1lsetxattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4, jlong jarg5, jint jarg6) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  void *arg4 = (void *) 0 ;
  size_t arg5 ;
  int arg6 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(void **)&jarg4; 
  arg5 = (size_t)jarg5; 
  arg6 = (int)jarg6; 
  result = (int)glfs_lsetxattr(arg1,(char const *)arg2,(char const *)arg3,(void const *)arg4,arg5,arg6);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fsetxattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4, jint jarg5) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  char *arg2 = (char *) 0 ;
  void *arg3 = (void *) 0 ;
  size_t arg4 ;
  int arg5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(void **)&jarg3; 
  arg4 = (size_t)jarg4; 
  arg5 = (int)jarg5; 
  result = (int)glfs_fsetxattr(arg1,(char const *)arg2,(void const *)arg3,arg4,arg5);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1removexattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)glfs_removexattr(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1lremovexattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)glfs_lremovexattr(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fremovexattr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)glfs_fremovexattr(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fallocate(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  int arg2 ;
  off_t arg3 ;
  size_t arg4 ;
  off_t *argp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = (int)jarg2; 
  argp3 = *(off_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (size_t)jarg4; 
  result = (int)glfs_fallocate(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1discard(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  off_t arg2 ;
  size_t arg3 ;
  off_t *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  argp2 = *(off_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  result = (int)glfs_discard(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1discard_1async(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  off_t arg2 ;
  size_t arg3 ;
  glfs_io_cbk arg4 = (glfs_io_cbk) 0 ;
  void *arg5 = (void *) 0 ;
  off_t *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  argp2 = *(off_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(glfs_io_cbk *)&jarg4; 
  arg5 = *(void **)&jarg5; 
  result = (int)glfs_discard_async(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1getcwd(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jstring jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  result = (char *)glfs_getcwd(arg1,arg2,arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1chdir(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)glfs_chdir(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1fchdir(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  result = (int)glfs_fchdir(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1realpath(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jstring jresult = 0 ;
  glfs_t *arg1 = (glfs_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (char *)glfs_realpath(arg1,(char const *)arg2,arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1posix_1lock(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jint jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  int arg2 ;
  struct flock *arg3 = (struct flock *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(struct flock **)&jarg3; 
  result = (int)glfs_posix_lock(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gluster_hadoop_glfsJNI_glfs_1dup(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  glfs_fd_t *arg1 = (glfs_fd_t *) 0 ;
  glfs_fd_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(glfs_fd_t **)&jarg1; 
  result = (glfs_fd_t *)glfs_dup(arg1);
  *(glfs_fd_t **)&jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

