/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gluster.hadoop;

public class glfsJNI {
  public final static native long glfs_new(String jarg1);
  public final static native int glfs_set_volfile(long jarg1, String jarg2);
  public final static native int glfs_set_volfile_server(long jarg1, String jarg2, String jarg3, int jarg4);
  public final static native int glfs_set_logging(long jarg1, String jarg2, int jarg3);
  public final static native int glfs_init(long jarg1);
  public final static native int glfs_fini(long jarg1);
  public final static native long glfs_open(long jarg1, String jarg2, int jarg3);
  public final static native long glfs_creat(long jarg1, String jarg2, int jarg3, long jarg4);
  public final static native int glfs_close(long jarg1);
  public final static native long glfs_from_glfd(long jarg1);
  public final static native int glfs_set_xlator_option(long jarg1, String jarg2, String jarg3, String jarg4);
  public final static native long glfs_read(long jarg1, long jarg2, long jarg3, int jarg4);
  public final static native long glfs_write(long jarg1, long jarg2, long jarg3, int jarg4);
  public final static native int glfs_read_async(long jarg1, long jarg2, long jarg3, int jarg4, long jarg5, long jarg6);
  public final static native int glfs_write_async(long jarg1, long jarg2, long jarg3, int jarg4, long jarg5, long jarg6);
  public final static native long glfs_readv(long jarg1, long jarg2, int jarg3, int jarg4);
  public final static native long glfs_writev(long jarg1, long jarg2, int jarg3, int jarg4);
  public final static native int glfs_readv_async(long jarg1, long jarg2, int jarg3, int jarg4, long jarg5, long jarg6);
  public final static native int glfs_writev_async(long jarg1, long jarg2, int jarg3, int jarg4, long jarg5, long jarg6);
  public final static native long glfs_pread(long jarg1, long jarg2, long jarg3, long jarg4, int jarg5);
  public final static native long glfs_pwrite(long jarg1, long jarg2, long jarg3, long jarg4, int jarg5);
  public final static native int glfs_pread_async(long jarg1, long jarg2, long jarg3, long jarg4, int jarg5, long jarg6, long jarg7);
  public final static native int glfs_pwrite_async(long jarg1, long jarg2, int jarg3, long jarg4, int jarg5, long jarg6, long jarg7);
  public final static native long glfs_preadv(long jarg1, long jarg2, int jarg3, long jarg4, int jarg5);
  public final static native long glfs_pwritev(long jarg1, long jarg2, int jarg3, long jarg4, int jarg5);
  public final static native int glfs_preadv_async(long jarg1, long jarg2, int jarg3, long jarg4, int jarg5, long jarg6, long jarg7);
  public final static native int glfs_pwritev_async(long jarg1, long jarg2, int jarg3, long jarg4, int jarg5, long jarg6, long jarg7);
  public final static native long glfs_lseek(long jarg1, long jarg2, int jarg3);
  public final static native int glfs_truncate(long jarg1, String jarg2, long jarg3);
  public final static native int glfs_ftruncate(long jarg1, long jarg2);
  public final static native int glfs_ftruncate_async(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int glfs_lstat(long jarg1, String jarg2, long jarg3);
  public final static native int glfs_stat(long jarg1, String jarg2, long jarg3);
  public final static native int glfs_fstat(long jarg1, long jarg2);
  public final static native int glfs_fsync(long jarg1);
  public final static native int glfs_fsync_async(long jarg1, long jarg2, long jarg3);
  public final static native int glfs_fdatasync(long jarg1);
  public final static native int glfs_fdatasync_async(long jarg1, long jarg2, long jarg3);
  public final static native int glfs_access(long jarg1, String jarg2, int jarg3);
  public final static native int glfs_symlink(long jarg1, String jarg2, String jarg3);
  public final static native int glfs_readlink(long jarg1, String jarg2, String jarg3, long jarg4);
  public final static native int glfs_mknod(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native int glfs_mkdir(long jarg1, String jarg2, long jarg3);
  public final static native int glfs_unlink(long jarg1, String jarg2);
  public final static native int glfs_rmdir(long jarg1, String jarg2);
  public final static native int glfs_rename(long jarg1, String jarg2, String jarg3);
  public final static native int glfs_link(long jarg1, String jarg2, String jarg3);
  public final static native long glfs_opendir(long jarg1, String jarg2);
  public final static native int glfs_readdir_r(long jarg1, long jarg2, long jarg3);
  public final static native int glfs_readdirplus_r(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int glfs_telldir(long jarg1);
  public final static native void glfs_seekdir(long jarg1, int jarg2);
  public final static native int glfs_closedir(long jarg1);
  public final static native int glfs_statvfs(long jarg1, String jarg2, long jarg3);
  public final static native int glfs_chmod(long jarg1, String jarg2, long jarg3);
  public final static native int glfs_fchmod(long jarg1, long jarg2);
  public final static native int glfs_chown(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native int glfs_lchown(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native int glfs_fchown(long jarg1, long jarg2, long jarg3);
  public final static native int glfs_utimens(long jarg1, String jarg2, long jarg3);
  public final static native int glfs_lutimens(long jarg1, String jarg2, long jarg3);
  public final static native int glfs_futimens(long jarg1, long jarg2);
  public final static native long glfs_getxattr(long jarg1, String jarg2, String jarg3, long jarg4, long jarg5);
  public final static native long glfs_lgetxattr(long jarg1, String jarg2, String jarg3, long jarg4, long jarg5);
  public final static native long glfs_fgetxattr(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native long glfs_listxattr(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native long glfs_llistxattr(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native long glfs_flistxattr(long jarg1, long jarg2, long jarg3);
  public final static native int glfs_setxattr(long jarg1, String jarg2, String jarg3, long jarg4, long jarg5, int jarg6);
  public final static native int glfs_lsetxattr(long jarg1, String jarg2, String jarg3, long jarg4, long jarg5, int jarg6);
  public final static native int glfs_fsetxattr(long jarg1, String jarg2, long jarg3, long jarg4, int jarg5);
  public final static native int glfs_removexattr(long jarg1, String jarg2, String jarg3);
  public final static native int glfs_lremovexattr(long jarg1, String jarg2, String jarg3);
  public final static native int glfs_fremovexattr(long jarg1, String jarg2);
  public final static native int glfs_fallocate(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int glfs_discard(long jarg1, long jarg2, long jarg3);
  public final static native int glfs_discard_async(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native String glfs_getcwd(long jarg1, String jarg2, long jarg3);
  public final static native int glfs_chdir(long jarg1, String jarg2);
  public final static native int glfs_fchdir(long jarg1);
  public final static native String glfs_realpath(long jarg1, String jarg2, String jarg3);
  public final static native int glfs_posix_lock(long jarg1, int jarg2, long jarg3);
  public final static native long glfs_dup(long jarg1);
}
