/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gluster.hadoop;

public class glfs {
  public static SWIGTYPE_p_glfs_t glfs_new(String volname) {
    long cPtr = glfsJNI.glfs_new(volname);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glfs_t(cPtr, false);
  }

  public static int glfs_set_volfile(SWIGTYPE_p_glfs_t fs, String volfile) {
    return glfsJNI.glfs_set_volfile(SWIGTYPE_p_glfs_t.getCPtr(fs), volfile);
  }

  public static int glfs_set_volfile_server(SWIGTYPE_p_glfs_t fs, String transport, String host, int port) {
    return glfsJNI.glfs_set_volfile_server(SWIGTYPE_p_glfs_t.getCPtr(fs), transport, host, port);
  }

  public static int glfs_set_logging(SWIGTYPE_p_glfs_t fs, String logfile, int loglevel) {
    return glfsJNI.glfs_set_logging(SWIGTYPE_p_glfs_t.getCPtr(fs), logfile, loglevel);
  }

  public static int glfs_init(SWIGTYPE_p_glfs_t fs) {
    return glfsJNI.glfs_init(SWIGTYPE_p_glfs_t.getCPtr(fs));
  }

  public static int glfs_fini(SWIGTYPE_p_glfs_t fs) {
    return glfsJNI.glfs_fini(SWIGTYPE_p_glfs_t.getCPtr(fs));
  }

  public static SWIGTYPE_p_glfs_fd glfs_open(SWIGTYPE_p_glfs_t fs, String path, int flags) {
    long cPtr = glfsJNI.glfs_open(SWIGTYPE_p_glfs_t.getCPtr(fs), path, flags);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glfs_fd(cPtr, false);
  }

  public static SWIGTYPE_p_glfs_fd glfs_creat(SWIGTYPE_p_glfs_t fs, String path, int flags, SWIGTYPE_p_mode_t mode) {
    long cPtr = glfsJNI.glfs_creat(SWIGTYPE_p_glfs_t.getCPtr(fs), path, flags, SWIGTYPE_p_mode_t.getCPtr(mode));
    return (cPtr == 0) ? null : new SWIGTYPE_p_glfs_fd(cPtr, false);
  }

  public static int glfs_close(SWIGTYPE_p_glfs_fd fd) {
    return glfsJNI.glfs_close(SWIGTYPE_p_glfs_fd.getCPtr(fd));
  }

  public static SWIGTYPE_p_glfs_t glfs_from_glfd(SWIGTYPE_p_glfs_fd fd) {
    long cPtr = glfsJNI.glfs_from_glfd(SWIGTYPE_p_glfs_fd.getCPtr(fd));
    return (cPtr == 0) ? null : new SWIGTYPE_p_glfs_t(cPtr, false);
  }

  public static int glfs_set_xlator_option(SWIGTYPE_p_glfs_t fs, String xlator, String key, String value) {
    return glfsJNI.glfs_set_xlator_option(SWIGTYPE_p_glfs_t.getCPtr(fs), xlator, key, value);
  }

  public static SWIGTYPE_p_ssize_t glfs_read(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_void buf, long count, int flags) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_read(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_void.getCPtr(buf), count, flags), true);
  }

  public static SWIGTYPE_p_ssize_t glfs_write(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_void buf, long count, int flags) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_write(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_void.getCPtr(buf), count, flags), true);
  }

  public static int glfs_read_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_void buf, long count, int flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_read_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_void.getCPtr(buf), count, flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int glfs_write_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_void buf, long count, int flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_write_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_void.getCPtr(buf), count, flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static SWIGTYPE_p_ssize_t glfs_readv(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_iovec iov, int iovcnt, int flags) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_readv(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_iovec.getCPtr(iov), iovcnt, flags), true);
  }

  public static SWIGTYPE_p_ssize_t glfs_writev(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_iovec iov, int iovcnt, int flags) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_writev(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_iovec.getCPtr(iov), iovcnt, flags), true);
  }

  public static int glfs_readv_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_iovec iov, int count, int flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_readv_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_iovec.getCPtr(iov), count, flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int glfs_writev_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_iovec iov, int count, int flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_writev_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_iovec.getCPtr(iov), count, flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static SWIGTYPE_p_ssize_t glfs_pread(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_void buf, long count, SWIGTYPE_p_off_t offset, int flags) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_pread(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_void.getCPtr(buf), count, SWIGTYPE_p_off_t.getCPtr(offset), flags), true);
  }

  public static SWIGTYPE_p_ssize_t glfs_pwrite(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_void buf, long count, SWIGTYPE_p_off_t offset, int flags) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_pwrite(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_void.getCPtr(buf), count, SWIGTYPE_p_off_t.getCPtr(offset), flags), true);
  }

  public static int glfs_pread_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_void buf, long count, SWIGTYPE_p_off_t offset, int flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_pread_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_void.getCPtr(buf), count, SWIGTYPE_p_off_t.getCPtr(offset), flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int glfs_pwrite_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_void buf, int count, SWIGTYPE_p_off_t offset, int flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_pwrite_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_void.getCPtr(buf), count, SWIGTYPE_p_off_t.getCPtr(offset), flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static SWIGTYPE_p_ssize_t glfs_preadv(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_iovec iov, int iovcnt, SWIGTYPE_p_off_t offset, int flags) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_preadv(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_iovec.getCPtr(iov), iovcnt, SWIGTYPE_p_off_t.getCPtr(offset), flags), true);
  }

  public static SWIGTYPE_p_ssize_t glfs_pwritev(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_iovec iov, int iovcnt, SWIGTYPE_p_off_t offset, int flags) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_pwritev(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_iovec.getCPtr(iov), iovcnt, SWIGTYPE_p_off_t.getCPtr(offset), flags), true);
  }

  public static int glfs_preadv_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_iovec iov, int count, SWIGTYPE_p_off_t offset, int flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_preadv_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_iovec.getCPtr(iov), count, SWIGTYPE_p_off_t.getCPtr(offset), flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int glfs_pwritev_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_iovec iov, int count, SWIGTYPE_p_off_t offset, int flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_pwritev_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_iovec.getCPtr(iov), count, SWIGTYPE_p_off_t.getCPtr(offset), flags, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static SWIGTYPE_p_off_t glfs_lseek(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_off_t offset, int whence) {
    return new SWIGTYPE_p_off_t(glfsJNI.glfs_lseek(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_off_t.getCPtr(offset), whence), true);
  }

  public static int glfs_truncate(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_off_t length) {
    return glfsJNI.glfs_truncate(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_off_t.getCPtr(length));
  }

  public static int glfs_ftruncate(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_off_t length) {
    return glfsJNI.glfs_ftruncate(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_off_t.getCPtr(length));
  }

  public static int glfs_ftruncate_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_off_t length, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_ftruncate_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_off_t.getCPtr(length), SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int glfs_lstat(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_stat buf) {
    return glfsJNI.glfs_lstat(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_stat.getCPtr(buf));
  }

  public static int glfs_stat(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_stat buf) {
    return glfsJNI.glfs_stat(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_stat.getCPtr(buf));
  }

  public static int glfs_fstat(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_stat buf) {
    return glfsJNI.glfs_fstat(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_stat.getCPtr(buf));
  }

  public static int glfs_fsync(SWIGTYPE_p_glfs_fd fd) {
    return glfsJNI.glfs_fsync(SWIGTYPE_p_glfs_fd.getCPtr(fd));
  }

  public static int glfs_fsync_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_fsync_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int glfs_fdatasync(SWIGTYPE_p_glfs_fd fd) {
    return glfsJNI.glfs_fdatasync(SWIGTYPE_p_glfs_fd.getCPtr(fd));
  }

  public static int glfs_fdatasync_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_fdatasync_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int glfs_access(SWIGTYPE_p_glfs_t fs, String path, int mode) {
    return glfsJNI.glfs_access(SWIGTYPE_p_glfs_t.getCPtr(fs), path, mode);
  }

  public static int glfs_symlink(SWIGTYPE_p_glfs_t fs, String oldpath, String newpath) {
    return glfsJNI.glfs_symlink(SWIGTYPE_p_glfs_t.getCPtr(fs), oldpath, newpath);
  }

  public static int glfs_readlink(SWIGTYPE_p_glfs_t fs, String path, String buf, long bufsiz) {
    return glfsJNI.glfs_readlink(SWIGTYPE_p_glfs_t.getCPtr(fs), path, buf, bufsiz);
  }

  public static int glfs_mknod(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_mode_t mode, SWIGTYPE_p_dev_t dev) {
    return glfsJNI.glfs_mknod(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_mode_t.getCPtr(mode), SWIGTYPE_p_dev_t.getCPtr(dev));
  }

  public static int glfs_mkdir(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_mode_t mode) {
    return glfsJNI.glfs_mkdir(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_mode_t.getCPtr(mode));
  }

  public static int glfs_unlink(SWIGTYPE_p_glfs_t fs, String path) {
    return glfsJNI.glfs_unlink(SWIGTYPE_p_glfs_t.getCPtr(fs), path);
  }

  public static int glfs_rmdir(SWIGTYPE_p_glfs_t fs, String path) {
    return glfsJNI.glfs_rmdir(SWIGTYPE_p_glfs_t.getCPtr(fs), path);
  }

  public static int glfs_rename(SWIGTYPE_p_glfs_t fs, String oldpath, String newpath) {
    return glfsJNI.glfs_rename(SWIGTYPE_p_glfs_t.getCPtr(fs), oldpath, newpath);
  }

  public static int glfs_link(SWIGTYPE_p_glfs_t fs, String oldpath, String newpath) {
    return glfsJNI.glfs_link(SWIGTYPE_p_glfs_t.getCPtr(fs), oldpath, newpath);
  }

  public static SWIGTYPE_p_glfs_fd glfs_opendir(SWIGTYPE_p_glfs_t fs, String path) {
    long cPtr = glfsJNI.glfs_opendir(SWIGTYPE_p_glfs_t.getCPtr(fs), path);
    return (cPtr == 0) ? null : new SWIGTYPE_p_glfs_fd(cPtr, false);
  }

  public static int glfs_readdir_r(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_dirent dirent, SWIGTYPE_p_p_dirent result) {
    return glfsJNI.glfs_readdir_r(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_dirent.getCPtr(dirent), SWIGTYPE_p_p_dirent.getCPtr(result));
  }

  public static int glfs_readdirplus_r(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_stat stat, SWIGTYPE_p_dirent dirent, SWIGTYPE_p_p_dirent result) {
    return glfsJNI.glfs_readdirplus_r(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_stat.getCPtr(stat), SWIGTYPE_p_dirent.getCPtr(dirent), SWIGTYPE_p_p_dirent.getCPtr(result));
  }

  public static int glfs_telldir(SWIGTYPE_p_glfs_fd fd) {
    return glfsJNI.glfs_telldir(SWIGTYPE_p_glfs_fd.getCPtr(fd));
  }

  public static void glfs_seekdir(SWIGTYPE_p_glfs_fd fd, int offset) {
    glfsJNI.glfs_seekdir(SWIGTYPE_p_glfs_fd.getCPtr(fd), offset);
  }

  public static int glfs_closedir(SWIGTYPE_p_glfs_fd fd) {
    return glfsJNI.glfs_closedir(SWIGTYPE_p_glfs_fd.getCPtr(fd));
  }

  public static int glfs_statvfs(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_statvfs buf) {
    return glfsJNI.glfs_statvfs(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_statvfs.getCPtr(buf));
  }

  public static int glfs_chmod(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_mode_t mode) {
    return glfsJNI.glfs_chmod(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_mode_t.getCPtr(mode));
  }

  public static int glfs_fchmod(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_mode_t mode) {
    return glfsJNI.glfs_fchmod(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_mode_t.getCPtr(mode));
  }

  public static int glfs_chown(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_uid_t uid, SWIGTYPE_p_gid_t gid) {
    return glfsJNI.glfs_chown(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_uid_t.getCPtr(uid), SWIGTYPE_p_gid_t.getCPtr(gid));
  }

  public static int glfs_lchown(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_uid_t uid, SWIGTYPE_p_gid_t gid) {
    return glfsJNI.glfs_lchown(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_uid_t.getCPtr(uid), SWIGTYPE_p_gid_t.getCPtr(gid));
  }

  public static int glfs_fchown(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_uid_t uid, SWIGTYPE_p_gid_t gid) {
    return glfsJNI.glfs_fchown(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_uid_t.getCPtr(uid), SWIGTYPE_p_gid_t.getCPtr(gid));
  }

  public static int glfs_utimens(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_timespec times) {
    return glfsJNI.glfs_utimens(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_timespec.getCPtr(times));
  }

  public static int glfs_lutimens(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_timespec times) {
    return glfsJNI.glfs_lutimens(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_timespec.getCPtr(times));
  }

  public static int glfs_futimens(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_timespec times) {
    return glfsJNI.glfs_futimens(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_timespec.getCPtr(times));
  }

  public static SWIGTYPE_p_ssize_t glfs_getxattr(SWIGTYPE_p_glfs_t fs, String path, String name, SWIGTYPE_p_void value, long size) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_getxattr(SWIGTYPE_p_glfs_t.getCPtr(fs), path, name, SWIGTYPE_p_void.getCPtr(value), size), true);
  }

  public static SWIGTYPE_p_ssize_t glfs_lgetxattr(SWIGTYPE_p_glfs_t fs, String path, String name, SWIGTYPE_p_void value, long size) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_lgetxattr(SWIGTYPE_p_glfs_t.getCPtr(fs), path, name, SWIGTYPE_p_void.getCPtr(value), size), true);
  }

  public static SWIGTYPE_p_ssize_t glfs_fgetxattr(SWIGTYPE_p_glfs_fd fd, String name, SWIGTYPE_p_void value, long size) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_fgetxattr(SWIGTYPE_p_glfs_fd.getCPtr(fd), name, SWIGTYPE_p_void.getCPtr(value), size), true);
  }

  public static SWIGTYPE_p_ssize_t glfs_listxattr(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_void value, long size) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_listxattr(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_void.getCPtr(value), size), true);
  }

  public static SWIGTYPE_p_ssize_t glfs_llistxattr(SWIGTYPE_p_glfs_t fs, String path, SWIGTYPE_p_void value, long size) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_llistxattr(SWIGTYPE_p_glfs_t.getCPtr(fs), path, SWIGTYPE_p_void.getCPtr(value), size), true);
  }

  public static SWIGTYPE_p_ssize_t glfs_flistxattr(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_void value, long size) {
    return new SWIGTYPE_p_ssize_t(glfsJNI.glfs_flistxattr(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_void.getCPtr(value), size), true);
  }

  public static int glfs_setxattr(SWIGTYPE_p_glfs_t fs, String path, String name, SWIGTYPE_p_void value, long size, int flags) {
    return glfsJNI.glfs_setxattr(SWIGTYPE_p_glfs_t.getCPtr(fs), path, name, SWIGTYPE_p_void.getCPtr(value), size, flags);
  }

  public static int glfs_lsetxattr(SWIGTYPE_p_glfs_t fs, String path, String name, SWIGTYPE_p_void value, long size, int flags) {
    return glfsJNI.glfs_lsetxattr(SWIGTYPE_p_glfs_t.getCPtr(fs), path, name, SWIGTYPE_p_void.getCPtr(value), size, flags);
  }

  public static int glfs_fsetxattr(SWIGTYPE_p_glfs_fd fd, String name, SWIGTYPE_p_void value, long size, int flags) {
    return glfsJNI.glfs_fsetxattr(SWIGTYPE_p_glfs_fd.getCPtr(fd), name, SWIGTYPE_p_void.getCPtr(value), size, flags);
  }

  public static int glfs_removexattr(SWIGTYPE_p_glfs_t fs, String path, String name) {
    return glfsJNI.glfs_removexattr(SWIGTYPE_p_glfs_t.getCPtr(fs), path, name);
  }

  public static int glfs_lremovexattr(SWIGTYPE_p_glfs_t fs, String path, String name) {
    return glfsJNI.glfs_lremovexattr(SWIGTYPE_p_glfs_t.getCPtr(fs), path, name);
  }

  public static int glfs_fremovexattr(SWIGTYPE_p_glfs_fd fd, String name) {
    return glfsJNI.glfs_fremovexattr(SWIGTYPE_p_glfs_fd.getCPtr(fd), name);
  }

  public static int glfs_fallocate(SWIGTYPE_p_glfs_fd fd, int keep_size, SWIGTYPE_p_off_t offset, long len) {
    return glfsJNI.glfs_fallocate(SWIGTYPE_p_glfs_fd.getCPtr(fd), keep_size, SWIGTYPE_p_off_t.getCPtr(offset), len);
  }

  public static int glfs_discard(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_off_t offset, long len) {
    return glfsJNI.glfs_discard(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_off_t.getCPtr(offset), len);
  }

  public static int glfs_discard_async(SWIGTYPE_p_glfs_fd fd, SWIGTYPE_p_off_t length, long lent, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void fn, SWIGTYPE_p_void data) {
    return glfsJNI.glfs_discard_async(SWIGTYPE_p_glfs_fd.getCPtr(fd), SWIGTYPE_p_off_t.getCPtr(length), lent, SWIGTYPE_p_f_p_struct_glfs_fd_ssize_t_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(data));
  }

  public static String glfs_getcwd(SWIGTYPE_p_glfs_t fs, String buf, long size) {
    return glfsJNI.glfs_getcwd(SWIGTYPE_p_glfs_t.getCPtr(fs), buf, size);
  }

  public static int glfs_chdir(SWIGTYPE_p_glfs_t fs, String path) {
    return glfsJNI.glfs_chdir(SWIGTYPE_p_glfs_t.getCPtr(fs), path);
  }

  public static int glfs_fchdir(SWIGTYPE_p_glfs_fd fd) {
    return glfsJNI.glfs_fchdir(SWIGTYPE_p_glfs_fd.getCPtr(fd));
  }

  public static String glfs_realpath(SWIGTYPE_p_glfs_t fs, String path, String resolved_path) {
    return glfsJNI.glfs_realpath(SWIGTYPE_p_glfs_t.getCPtr(fs), path, resolved_path);
  }

  public static int glfs_posix_lock(SWIGTYPE_p_glfs_fd fd, int cmd, SWIGTYPE_p_flock flock) {
    return glfsJNI.glfs_posix_lock(SWIGTYPE_p_glfs_fd.getCPtr(fd), cmd, SWIGTYPE_p_flock.getCPtr(flock));
  }

  public static SWIGTYPE_p_glfs_fd glfs_dup(SWIGTYPE_p_glfs_fd fd) {
    long cPtr = glfsJNI.glfs_dup(SWIGTYPE_p_glfs_fd.getCPtr(fd));
    return (cPtr == 0) ? null : new SWIGTYPE_p_glfs_fd(cPtr, false);
  }

}
