/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gluster.hadoop;

public class SWIGTYPE_p_stat {
  private long swigCPtr;

  protected SWIGTYPE_p_stat(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_stat() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_stat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

